---
chargen:
  achievements:
    created_character:
      type: story
      message: Created a character.
  allow_web_submit: true
  app_category: APP
  app_hold_status: HOLD
  app_resubmit_status: OPEN
  app_review_commands:
  - app %{name}
  - profile %{name}
  - bg %{name}
  - hooks %{name}
  - sheet %{name}
  approval_message: Congratulations!  Your application has been approved.  Type %xhonstage%xn
    to go forth and RP.  You may want to customize your character profile on the web
    portal.
  arrivals_category: New Arrivals
  bg_blurb: You don't need to write a novel. Just cover the basics. We encourage players to answer
    3 basic questions about their character. These questions should give us intimate insight into
    the character and what makes them, them.
    
    Example questions - 1) Why are they here? 2) What can't the character live without? 3) Why does
    the character do what they do? 4) What word best describes your character? 5) What would your
    character never do and why?
    
    If you desire to explore your character's background in more detail, you always have your character's
    wiki page to expand upon the things you write here. For approval purposes we ask that you keep things
    concise and simple, however.
  demographics_blurb: Demographics record your basic character info.
  desc_blurb: You can set both your main description, visible when people look at
    you, and a short description that shows your character at a glance.
  groups_blurb: Groups determine your character's affiliations.
  traits_blurb: Traits represent anything that stands out about your character, anything
    out of the ordinary. Powers, skills, talents, advantages, flaws, and weaknesses all 
    count as traits. Traits can be described individually or in groups. Either way, please
    keep their descriptions as concise as possible. Be sure to review other, approved,
    character's traits for examples of what we're looking for.
  hooks_blurb: RP Hooks are interesting things about your character that others can
    hook into for RP. This could be an odd personality quirk, a reputation your character
    has, or anything else that might inspire someone to connect with you. Looking
    around at other character's sheets can be a good way to get inspiration for RP
    Hooks.
  hooks_required: true
  icon_blurb: Your profile icon appears in scenes and the character gallery to show
    your character at a glance. Providing a profile icon is optional. You can upload
    additional character images once you're approved.
  post_approval_message: Please make sure they have a profile image for their log
    icon.
  rank_blurb: Military rank.
  rejection_message: Sorry, your character could not be approved at the present time
    for the reasons described below.  Please see %xhhelp app%xn for help making changes
    and resubmitting, and contact the person handling your application if you have
    any questions.
  shortcuts:
    chargen: cg
    cg/back: cg/prev
    cg/previous: cg/prev
    bg/approve: app/approve
    bg/reject: app/reject
    bg/submit: app/submit
    bg/unsubmit: app/unsubmit
    hooks: hook
    hook/delete: hook/remove
    hook/add: hook/set
  stages:
    start:
      title: Chargen Commands
      text: You can do chargen either on the Web Portal (help web portal) or in-game.  Please
        note, however, that while most things can be done on the Web Portal you must
        complete your character sheet in-game. The things you can do on the Web Portal
        include your background, description, rpg hooks, demographics, etc.%R%RIf
        you choose to use the in-game chargen, the %xccg%xn command will walk you
        through the necessary steps.%R%RYou can go back and forth through the steps
        of chargen as much as you want using %xccg/next%xn and %xccg/prev%xn.
    app:
      title: App Review
      text: The `app` command is your friend during chargen. It will alert you to
        things you may have forgotten to set, things that may have been valid when
        you set them but have become invalid since you've made changes to your character,
        etc.%r%r%xrRed%xn issues will almost certainly prevent your character from
        being approved (like forgetting to set your eye color).%r %r%xyYellow%xn issues
        are warnings; they might actually be OK if it fits the character concept.%r%rYour
        'app' screen will change depending on what template you choose later in character
        generation. Be sure to check the command often so you can remain as up to
        date on your app status as possible.
    client:
      help: client
    sheet:
      help: sheets
    demographics:
      help: demographics
    groups:
      help: groups
    background:
      help: backgrounds
    desc:
      help: descriptions
    hooks:
      help: hooks
    handles:
      help: handles
    profile:
      help: profile
    lastwill:
      help: idle_out
    attributes:
      help: attributes
    skills:
      help: skill_setting
    powers:
      help: powers
    pdesc:
      help: power_descriptions
    review:
      title: App Submission
      text: You've completed chargen!  Review your app one more time, and use `app/submit
        [<optional notes>]` to submit your character when ready.  The admins will
        make sure it's a good fit for the game's theme, that the skills are reasonable
        given the background, and that you haven't missed anything important in chargen.
        See `help apps` for additional help on the app review process.
  welcome_message: Please welcome %{name}, our latest %{universe} character to be
    approved!
